version: '3.3'
services:
  auth-service:
    image: node:16-alpine3.14
    container_name: auth_service
    depends_on:
      - database
      - redis
      - rabbitmq
      - elk
    restart: always
    working_dir: "/usr/src/app"
    command: "npm run docker"
    volumes:
      - ./auth-service:/usr/src/app
      - ./.env:/usr/src/services.env/.env:ro
      - ./logs/auth-service:/usr/service-logs
  counter-service:
    image: node:16-alpine3.14
    container_name: counter_service
    depends_on:
      - database
      - redis
      - rabbitmq
      - elk
    restart: always
    working_dir: "/usr/src/app"
    command: "npm run docker"
    volumes:
      - ./counter-service:/usr/src/app
      - ./.env:/usr/src/services.env/.env:ro
      - ./logs/counter-service:/usr/service-logs
  database:
    image: postgres:14-alpine
    container_name: services_db
    restart: always
    volumes:
      - ./databases/pg:/var/lib/postgresql/data
      - ./databases/initialization/pg:/docker-entrypoint-initdb.d
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
  redis:
    command: "redis-server /usr/local/etc/redis/redis.conf --requirepass $REDIS_PASSWORD"
    image: redis:7.0.0-alpine
    container_name: redis_server
    restart: always
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/cache:/data
    env_file:
      - .env
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:3.10.7
    container_name: rabbitmq_server
    restart: always
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
  nginx:
    image: nginx:1.21.6-alpine
    container_name: nginx_server
    depends_on:
      - auth-service
      - counter-service
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cache:/var/lib/redis
    ports:
      - 80:80
    env_file:
      - .env
  elk: 
    image: sebp/elk
    container_name: elk_server
    restart: always
    volumes:
      - ./elk-data:/var/lib/elasticsearch
    ports:
      - 5601:5601
      - 9200:9200
      - 9300:9300
      - 5044:5044
  filebeat:
    image: elastic/filebeat:8.3.3
    command: -e --strict.perms=false
    container_name: filebeat_server
    restart: always
    volumes:
      - ./filebeat/conf/docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./filebeat/logstash-beats.crt:/etc/pki/tls/certs/logstash-beats.crt:ro
      - ./logs:/var/services_logs
    labels:
      co.elastic.logs/json.keys_under_root: true
      co.elastic.logs/json.overwrite_keys: true
      co.elastic.logs/json.add_error_key: true
      co.elastic.logs/json.expand_keys: true
    depends_on:
      - elk